### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by MattTheTekie** [VenithNET/VENITH.NET#1]
TDK 2.0
- [x] Let @DigitalCheese finish up his rewrite.
- [x] I will work on the backend.
- [x] Profit! nya~

**Comment by DigitalCheese** [comment]
owo

**Comment by MattTheTekie** [comment]
TDKPaint 2.0 is out now! nya~ @DigitalCheese

**Comment by MattTheTekie** [comment]
- [ ] Comment system
- [ ] Fix up links in TDKHome & TDKPaint
- [ ] Profit! nya~

**Comment by MattTheTekie** [comment]
TDK 2.2

- [ ] Profile system

**Comment by MattTheTekie** [comment]
> owo

uwu

**Comment by MattTheTekie** [comment]
> TDK 2.1
> 
> * [ ]  Comment system.
> * [ ]  Profile system.
> * [15%] Fix up links in TDKHome & TDKPaint.
> * [ ]  Profit! nya~

Scrap it! Not worth the time. However I got a lot done, and the site is much better then before!
